version: "3.9"

services:

  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: noise_timescaledb
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data

  mqtt:
    image: eclipse-mosquitto:2
    container_name: noise_mqtt
    restart: unless-stopped
    ports:
      - "${MQTT_PORT}:1883"
    volumes:
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log

  yggio_ingester:
    build: ./services/yggio_api      
    container_name: yggio_ingester
    restart: unless-stopped          
    env_file:
      - ./services/yggio_api/.env    
    depends_on:
      - timescaledb
    volumes:
      - ./services/yggio_api:/app

  frontend_api:
    build: ./services/frontend_api
    container_name: frontend_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - timescaledb
    env_file:
      - ./services/yggio_api/.env
    volumes:
      - ./services/frontend_api:/app

  frontend:
    build: ./services/frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - frontend_api
    restart: always

volumes:
  timescale_data:
  mosquitto_data:
  mosquitto_log: