// English translations for the Malmö Noise Dashboard
const en = {
  // Sidebar
  sidebar: {
    logo: 'Malmö Noise',
    logoSub: 'Monitoring',
    overview: 'Overview',
    sensorMap: 'Sensor Map',
    liveReadings: 'Live Readings',
    alerts: 'Alerts & Outliers',
    sensorHealth: 'Sensor Health',
    reports: 'Reports',
    settings: 'Settings',
    notifications: 'Notifications',
    system: 'System',
  },

  // Header
  header: {
    searchPlaceholder: 'Ask AI about sensor data, noise levels or get insights...',
    ask: 'Ask',
    admin: 'Admin',
  },

  // Overview page
  overview: {
    title: 'Overview',
    subtitle: 'System-wide summary of noise monitoring',
    activeSensors: 'Active sensors',
    activeSensorsSubtitle: 'With GPS coordinates',
    maxNoise: 'Current highest level',
    maxNoiseSubtitle: 'Max live reading across all sensors',
    maxNoiseSensor: 'Sensor ID of highest',
    maxNoiseSensorSubtitle: 'Sensor reporting highest reading',
    activeAlerts: 'Active alerts',
    activeAlertsSubtitle: 'Sensors at 80 dB or above',
    sensorHealth: 'Sensor health',
    sensorHealthSubtitle: 'Active in last 2 hours',
    chartTitle: 'Noise Level Overview',
    last1h: 'Last 1h',
    last6h: 'Last 6h',
    last24h: 'Last 24h',
    export: 'Export',
    range1h: '1 hour — 1-minute averages',
    range6h: '6 hours — 1-hour averages',
    range24h: '24 hours — 1-hour averages',
    loading: 'Loading dashboard data...',
    errorLoading: 'Error loading data:',
    noData: 'No historical data available',
  },

  // Sensor Map page
  sensorMap: {
    title: 'Sensor Map',
    subtitle: 'Sensor locations and current noise levels',
    hideHeatZones: 'Hide heat zones',
    showHeatZones: 'Show heat zones',
    loading: 'Loading map data...',
    sensorDetails: 'Sensor Details',
    sensorId: 'Sensor ID',
    location: 'Location',
    currentLevel: 'Current level',
    lastUpdated: 'Last updated',
    coordinates: 'Coordinates',
    clearSelection: 'Clear selection',
    clickPrompt: 'Click a sensor on the map to view details',
    legend: 'Noise Level Legend',
    legendNormal: 'Normal',
    legendModerate: 'Elevated',
    legendHigh: 'Warning',
    legendCritical: 'Critical',
  },

  // Live Readings page
  liveReadings: {
    title: 'Live Readings',
    liveIndicator: 'Live — updates every 10 seconds',
    loading: 'Loading sensor data...',
    noData: 'No sensor readings available',
    guidelines: 'Evaluation Guidelines',
    levelNormal: 'Normal',
    levelModerate: 'Elevated',
    levelHigh: 'Approaching attention required',
    levelCritical: 'Immediate attention required',
    descNormal: 'Safe ambient noise',
    descModerate: 'Elevated but acceptable',
    descHigh: 'Approaching unsafe levels',
    descCritical: 'Requires immediate action',
  },

  // Alerts & Outliers page
  alerts: {
    title: 'Alerts & Outliers',
    subtitle: 'Last 24 hours — outlier noise measurements',
    criticalBanner: (n) => `Critical alert: ${n} sensor${n !== 1 ? 's' : ''} exceeded 90 dB in the last 24 hours`,
    warningBanner: (n) => `Warning: ${n} reading${n !== 1 ? 's' : ''} between 80–90 dB detected`,
    tableTitle: 'Noise Measurement Outliers',
    filterAll: (n) => `All (${n})`,
    filterHigh: (n) => `${n} High outlier${n !== 1 ? 's' : ''}`,
    filterLow: (n) => `${n} Low outlier${n !== 1 ? 's' : ''}`,
    exportCsv: 'Export CSV',
    loading: 'Loading alerts...',
    noOutliers: 'No outliers found in the last 24 hours',
    colSensor: 'Sensor',
    colLocation: 'Location',
    colReading: 'Reading',
    colType: 'Type',
    colTimestamp: 'Timestamp',
    colNotes: 'Notes',
    typeCritical: 'Immediate attention required',
    typeHigh: 'Approaching attention required',
    typeLow: 'Low',
  },

  // Sensor Health page
  sensorHealth: {
    title: 'Sensor Health',
    subtitle: 'Status overview for all registered sensors',
    exportReport: 'Export report',
    statusOperational: 'Operational',
    statusWarning: 'Degraded',
    statusCritical: 'Poor',
    totalSensors: 'Total sensors',
    tableTitle: 'Sensor Table',
    colSensorId: 'Sensor ID',
    colLocation: 'Location',
    colAvailability: 'Availability (24 h)',
    colMaxGap: 'Max Gap',
    colStatus: 'Status',
    colLastSeen: 'Last seen',
    colReadings: 'Readings (24 h)',
    availabilityHint: 'Data Availability Rate — observed readings in last 24 h vs. expected count derived from this sensor\'s median inter-reading gap over the last 30 days',
    maxGapHint: 'Longest consecutive silence between readings in the last 24 h',
    never: 'Never',
    loading: 'Loading...',
    noData: '—',
  },

  // Reports page
  reports: {
    title: 'Reports',
    subtitle: 'Select a report type, apply filters, preview the data, then download as CSV or PDF.',
    step1: 'Choose report type',
    step2: 'Set filters',
    step3: 'Preview & download',
    timeRange: 'Time range',
    sensor: 'Sensor',
    allSensors: 'All sensors',
    noFiltersNeeded: 'No filters required for this report type.',
    loading: 'Loading data…',
    noData: 'No data found for the selected filters.',
    rowsReady: 'rows ready to export',
    downloadCsv: 'Download CSV',
    downloadPdf: 'Download PDF',
    types: {
      summary:      'System Summary',
      alerts:       'Alerts & Outliers',
      sensorHealth: 'Sensor Health',
      rawReadings:  'Raw Readings',
    },
    descs: {
      summary:      'Totals, averages and ranges per sensor',
      alerts:       'All readings ≥ 80 dB or < 25 dB in the last 24 h',
      sensorHealth: 'Status, battery and last-seen for every sensor',
      rawReadings:  'Up to 500 raw measurements (all or one sensor)',
    },
  },

  // Settings page
  settings: {
    title: 'Settings',
    subtitle: 'Configure notifications, thresholds and system settings',
    navNotifications: 'Notifications',
    navThresholds: 'Thresholds',
    navDashboard: 'Dashboard',
    navUsers: 'Users & access',
    navSecurity: 'Security',
    dashboardTitle: 'Dashboard Preferences',
    dashboardSubtitle: 'Control how the dashboard behaves',
    liveRefreshLabel: 'Live readings refresh interval',
    liveRefreshDesc: 'How often the Live Readings page auto-fetches new sensor data',
    overviewRangeLabel: 'Overview default time range',
    overviewRangeDesc: 'Which time window the Overview chart opens on',
    darTitle: 'Sensor Health Thresholds',
    darSubtitle: 'DAR boundaries used to classify sensor status',
    darOperationalLabel: 'Operational threshold (DAR %)',
    darOperationalDesc: 'Sensors at or above this availability rate are classified as Operational',
    darWarningLabel: 'Warning / Poor boundary (DAR %)',
    darWarningDesc: 'Sensors below this rate are classified as Poor; above it as Degraded',
    seconds: 's',
    hours: 'h',
    notifTitle: 'Notification settings',
    notifSubtitle: 'Choose which notifications you want to receive',
    prefCriticalLabel: 'Critical alerts',
    prefCriticalDesc: 'Immediate notification when sensors exceed the critical threshold',
    prefDailyLabel: 'Daily summary',
    prefDailyDesc: 'Daily summary of noise levels and sensor status',
    prefWeeklyLabel: 'Weekly report',
    prefWeeklyDesc: 'Weekly analysis report with trends and insights',
    prefMaintenanceLabel: 'Maintenance reminders',
    prefMaintenanceDesc: 'Alerts when sensors need a maintenance check',
    thresholdsTitle: 'Alert thresholds',
    thresholdsSubtitle: 'Set the dB levels that trigger alerts',
    thresholdHighLabel: 'Warning threshold (default 80 dB)',
    thresholdHighDesc: 'Triggers a warning alert — readings at or above this level (80–90 dB range)',
    thresholdCriticalLabel: 'Critical threshold (default 90 dB)',
    thresholdCriticalDesc: 'Triggers a critical alert — readings at or above this level (90+ dB)',
    usersComingSoon: 'User and access management coming soon',
    securityComingSoon: 'Security settings coming soon',
    cancel: 'Cancel',
    saveChanges: 'Save changes',
    saved: 'Saved!',
  },

  // Noise level labels
  levels: {
    critical: 'Critical',
    high: 'High',
    moderate: 'Moderate',
    normal: 'Normal',
  },

  // Placeholder pages
  placeholder: {
    notImplemented: 'This section is not yet implemented.',
    notificationsDesc: 'Alert notifications and event history',
    systemDesc: 'System status and diagnostics',
  },
};

export default en;
