// English translations for the Malmö Noise Dashboard
const en = {
  // Sidebar
  sidebar: {
    logo: 'Malmö Noise',
    logoSub: 'Monitoring',
    overview: 'Overview',
    sensorMap: 'Sensor Map',
    liveReadings: 'Live Readings',
    alerts: 'Alerts & Outliers',
    sensorHealth: 'Sensor Health',
    dataAnalysis: 'Data Analysis',
    reports: 'Reports',
    settings: 'Settings',
    notifications: 'Notifications',
    system: 'System',
  },

  // Header
  header: {
    searchPlaceholder: 'Ask AI about sensor data, noise levels or get insights...',
    ask: 'Ask',
    admin: 'Admin',
  },

  // Overview page
  overview: {
    title: 'Overview',
    subtitle: 'System-wide summary of noise monitoring',
    activeSensors: 'Active sensors',
    activeSensorsSubtitle: 'With GPS coordinates',
    avgNoise: 'Average noise level',
    avgNoiseSubtitle: 'Current average across all sensors',
    peakNoise: 'Current highest',
    peakNoiseSubtitle: 'Sensor:',
    activeAlerts: 'Active alerts',
    activeAlertsSubtitle: 'Sensors above 80 dB or below 25 dB',
    sensorHealth: 'Sensor health',
    sensorHealthSubtitle: 'Active in last 2 hours',
    chartTitle: 'Noise Level Overview',
    last1h: 'Last 1h',
    last6h: 'Last 6h',
    last24h: 'Last 24h',
    export: 'Export',
    range1h: '1 hour — 1-minute averages',
    range6h: '6 hours — 1-hour averages',
    range24h: '24 hours — 1-hour averages',
    loading: 'Loading dashboard data...',
    errorLoading: 'Error loading data:',
    noData: 'No historical data available',
  },

  // Sensor Map page
  sensorMap: {
    title: 'Sensor Map',
    subtitle: 'Sensor locations and current noise levels',
    hideHeatZones: 'Hide heat zones',
    showHeatZones: 'Show heat zones',
    loading: 'Loading map data...',
    sensorDetails: 'Sensor Details',
    sensorId: 'Sensor ID',
    location: 'Location',
    currentLevel: 'Current level',
    lastUpdated: 'Last updated',
    coordinates: 'Coordinates',
    clearSelection: 'Clear selection',
    clickPrompt: 'Click a sensor on the map to view details',
    legend: 'Noise Level Legend',
    legendNormal: 'Normal',
    legendModerate: 'Moderate',
    legendHigh: 'High',
  },

  // Live Readings page
  liveReadings: {
    title: 'Live Readings',
    liveIndicator: 'Live — updates every 10 seconds',
    loading: 'Loading sensor data...',
    noData: 'No sensor readings available',
    guidelines: 'Evaluation Guidelines',
    levelNormal: 'Normal',
    levelModerate: 'Elevated',
    levelHigh: 'Approaching attention required',
    levelCritical: 'Immediate attention required',
    descNormal: 'Normal ambient noise level',
    descModerate: 'Elevated above background noise',
    descHigh: 'Action may be needed — monitor closely',
    descCritical: 'Immediate attention required',
  },

  // Alerts & Outliers page
  alerts: {
    title: 'Alerts & Outliers',
    subtitle: 'Last 24 hours — outlier noise measurements',
    criticalBanner: (n) => `Critical alert: ${n} sensor${n !== 1 ? 's' : ''} exceeded 90 dB in the last 24 hours`,
    warningBanner: (n) => `Warning: ${n} reading${n !== 1 ? 's' : ''} between 80–90 dB detected`,
    tableTitle: 'Noise Measurement Outliers',
    filterAll: (n) => `All (${n})`,
    filterHigh: (n) => `${n} High outlier${n !== 1 ? 's' : ''}`,
    filterLow: (n) => `${n} Low outlier${n !== 1 ? 's' : ''}`,
    exportCsv: 'Export CSV',
    loading: 'Loading alerts...',
    noOutliers: 'No outliers found in the last 24 hours',
    colSensor: 'Sensor',
    colLocation: 'Location',
    colReading: 'Reading',
    colType: 'Type',
    colTimestamp: 'Timestamp',
    colNotes: 'Notes',
    typeCritical: 'Critical',
    typeWarning: 'Warning',
    typeLow: 'Low',
  },

  // Sensor Health page
  sensorHealth: {
    title: 'Sensor Health',
    subtitle: 'Status overview for all registered sensors',
    exportReport: 'Export report',
    statusOperational: 'Operational',
    statusWarning: 'Warning',
    statusCritical: 'Critical',
    totalSensors: 'Total sensors',
    tableTitle: 'Sensor Table',
    colSensorId: 'Sensor ID',
    colLocation: 'Location',
    colBattery: 'Battery',
    colSignal: 'Signal',
    colStatus: 'Status',
    colLastSeen: 'Last seen',
    signalStrong: 'Strong',
    signalModerate: 'Moderate',
    signalWeak: 'Weak',
    never: 'Never',
    loading: 'Loading...',
  },

  // Data Analysis page
  dataAnalysis: {
    title: 'Data Analysis',
    subtitle: 'Explore noise patterns and trends',
    newAnalysis: 'New analysis',
    filters: 'Filters',
    exportAll: 'Export all',
    templatesTitle: 'Analysis Templates',
    templateTimeseries: 'Daily average by location',
    templatePeak: 'Rush hour analysis',
    templateComparison: 'Sensor comparison',
    templateWeekly: 'Weekly trends',
    typeLineChart: 'Line chart',
    typeBarChart: 'Bar chart',
    typeAreaChart: 'Area chart',
    timeRange: 'Time range',
    last1h: 'Last 1 hour',
    last6h: 'Last 6 hours',
    last24h: 'Last 24 hours',
    modeAvg: 'Average',
    modePeak: 'Peak',
    distributionTitle: 'Reading Distribution',
    defaultChartTitle: 'Hourly noise analysis',
    loading: 'Loading chart data...',
    loadingDist: 'Loading...',
    noData: 'No data available',
    tooltipAvg: 'Avg',
    tooltipReadings: 'Readings',
  },

  // Reports page
  reports: {
    title: 'Reports',
    subtitle: 'Generate, schedule and manage noise monitoring reports',
    generateTitle: 'Generate report',
    generateDesc: 'Create a new report from current data',
    generateBtn: 'Generate now',
    scheduleTitle: 'Schedule report',
    scheduleDesc: 'Configure automatic recurring reports',
    scheduleBtn: 'Set schedule',
    emailTitle: 'Email report',
    emailDesc: 'Send reports directly to recipients',
    emailBtn: 'Configure email',
    scheduledTitle: 'Scheduled reports',
    colReportName: 'Report name',
    colFrequency: 'Frequency',
    colStatus: 'Status',
    colNextRun: 'Next run',
    colActions: 'Actions',
    editBtn: 'Edit',
    pauseBtn: 'Pause',
    recentTitle: 'Recent reports',
    viewAll: 'View all',
    colDate: 'Date',
    colFormat: 'Format',
    colSize: 'Size',
    downloadLatest: 'Download latest',
    statusActive: 'Active',
    // Scheduled report names & frequencies
    dailyName: 'Daily noise summary',
    weeklyName: 'Weekly analysis report',
    monthlyName: 'Monthly sensor health',
    dailyFreq: 'Every day at 08:00',
    weeklyFreq: 'Every Monday at 09:00',
    monthlyFreq: 'First day of each month',
    nextTomorrow: 'Tomorrow 08:00',
    nextMon: 'Mon 09:00',
    nextApr: 'Apr 1 08:00',
    // Recent report names
    sensorHealthReport: 'Sensor health report',
  },

  // Settings page
  settings: {
    title: 'Settings',
    subtitle: 'Configure notifications, thresholds and system settings',
    navNotifications: 'Notifications',
    navThresholds: 'Thresholds',
    navUsers: 'Users & access',
    navSecurity: 'Security',
    notifTitle: 'Notification settings',
    notifSubtitle: 'Choose which notifications you want to receive',
    prefCriticalLabel: 'Critical alerts',
    prefCriticalDesc: 'Immediate notification when sensors exceed the critical threshold',
    prefDailyLabel: 'Daily summary',
    prefDailyDesc: 'Daily summary of noise levels and sensor status',
    prefWeeklyLabel: 'Weekly report',
    prefWeeklyDesc: 'Weekly analysis report with trends and insights',
    prefMaintenanceLabel: 'Maintenance reminders',
    prefMaintenanceDesc: 'Alerts when sensors need a maintenance check',
    thresholdsTitle: 'Alert thresholds',
    thresholdsSubtitle: 'Set the dB levels that trigger alerts',
    thresholdHighLabel: 'High noise level',
    thresholdHighDesc: 'Triggers a warning alert',
    thresholdCriticalLabel: 'Critical noise level',
    thresholdCriticalDesc: 'Triggers a critical alert',
    usersComingSoon: 'User and access management coming soon',
    securityComingSoon: 'Security settings coming soon',
    cancel: 'Cancel',
    saveChanges: 'Save changes',
    saved: 'Saved!',
  },

  // Noise level labels
  levels: {
    critical: 'Critical',
    high: 'High',
    moderate: 'Moderate',
    normal: 'Normal',
  },

  // Placeholder pages
  placeholder: {
    notImplemented: 'This section is not yet implemented.',
    notificationsDesc: 'Alert notifications and event history',
    systemDesc: 'System status and diagnostics',
  },
};

export default en;
