// Swedish translations for the Malmö Noise Dashboard
const sv = {
  // Sidebar
  sidebar: {
    logo: 'Malmö Buller',
    logoSub: 'Övervakning',
    overview: 'Översikt',
    sensorMap: 'Sensorkarta',
    liveReadings: 'Livemätningar',
    alerts: 'Larm & Avvikelser',
    sensorHealth: 'Sensorhälsa',
    dataAnalysis: 'Dataanalys',
    reports: 'Rapporter',
    settings: 'Inställningar',
    notifications: 'Notifikationer',
    system: 'System',
  },

  // Header
  header: {
    searchPlaceholder: 'Fråga AI om sensordata, bullernivåer eller få insikter...',
    ask: 'Fråga',
    admin: 'Admin',
  },

  // Overview page
  overview: {
    title: 'Översikt',
    subtitle: 'Systemövergripande sammanfattning av bullerovervakning',
    activeSensors: 'Aktiva sensorer',
    activeSensorsSubtitle: 'Med GPS-koordinater',
    avgNoise: 'Genomsnittlig bullernivå',
    avgNoiseSubtitle: 'Aktuellt genomsnitt för alla sensorer',
    peakNoise: 'Aktuellt högst',
    peakNoiseSubtitle: 'Sensor:',
    activeAlerts: 'Aktiva larm',
    activeAlertsSubtitle: 'Sensorer över 80 dB eller under 25 dB',
    sensorHealth: 'Sensorhälsa',
    sensorHealthSubtitle: 'Aktiva senaste 2 timmarna',
    chartTitle: 'Bullernivsöversikt',
    last1h: 'Senaste 1h',
    last6h: 'Senaste 6h',
    last24h: 'Senaste 24h',
    export: 'Exportera',
    range1h: '1 timme — 1 minuts genomsnitt',
    range6h: '6 timmar — 1 timmes genomsnitt',
    range24h: '24 timmar — 1 timmes genomsnitt',
    loading: 'Laddar instrumentpaneldata...',
    errorLoading: 'Fel vid laddning av data:',
    noData: 'Ingen historisk data tillgänglig',
  },

  // Sensor Map page
  sensorMap: {
    title: 'Sensorkarta',
    subtitle: 'Sensorplatser och aktuella bullernivåer',
    hideHeatZones: 'Dölj värmezoner',
    showHeatZones: 'Visa värmezoner',
    loading: 'Laddar kartdata...',
    sensorDetails: 'Sensordetaljer',
    sensorId: 'Sensor-ID',
    location: 'Plats',
    currentLevel: 'Aktuell nivå',
    lastUpdated: 'Senast uppdaterad',
    coordinates: 'Koordinater',
    clearSelection: 'Rensa val',
    clickPrompt: 'Klicka på en sensor på kartan för att se detaljer',
    legend: 'Bullernivslegend',
    legendNormal: 'Normal',
    legendModerate: 'Måttlig',
    legendHigh: 'Hög',
  },

  // Live Readings page
  liveReadings: {
    title: 'Livemätningar',
    liveIndicator: 'Livemätning — uppdateras var 10:e sekund',
    loading: 'Laddar sensordata...',
    noData: 'Inga sensormätningar tillgängliga',
    guidelines: 'Utvärderingsriktlinjer',
    levelNormal: 'Normal',
    levelModerate: 'Förhöjd',
    levelHigh: 'Kräver uppmärksamhet',
    levelCritical: 'Omedelbar uppmärksamhet krävs',
    descNormal: 'Normal omgivningsbullernivå',
    descModerate: 'Förhöjd över bakgrundsbuller',
    descHigh: 'Åtgärd kan krävas — övervaka noga',
    descCritical: 'Omedelbar uppmärksamhet krävs',
  },

  // Alerts & Outliers page
  alerts: {
    title: 'Larm & Avvikelser',
    subtitle: 'Senaste 24 timmarna — avvikande bullermätningar',
    criticalBanner: (n) => `Kritiskt larm: ${n} sensor${n !== 1 ? 'er' : ''} överskred 90 dB de senaste 24 timmarna`,
    warningBanner: (n) => `Varning: ${n} mätning${n !== 1 ? 'ar' : ''} mellan 80–90 dB detekterades`,
    tableTitle: 'Bullermätningsavvikelser',
    filterAll: (n) => `Alla (${n})`,
    filterHigh: (n) => `${n} Höga avvikelser`,
    filterLow: (n) => `${n} Låga avvikelser`,
    exportCsv: 'Exportera CSV',
    loading: 'Laddar larm...',
    noOutliers: 'Inga avvikelser hittades de senaste 24 timmarna',
    colSensor: 'Sensor',
    colLocation: 'Plats',
    colReading: 'Mätning',
    colType: 'Typ',
    colTimestamp: 'Tidsstämpel',
    colNotes: 'Anteckningar',
    typeCritical: 'Kritisk',
    typeWarning: 'Varning',
    typeLow: 'Låg',
  },

  // Sensor Health page
  sensorHealth: {
    title: 'Sensorhälsa',
    subtitle: 'Statusöversikt för alla registrerade sensorer',
    exportReport: 'Exportera rapport',
    statusOperational: 'Operativ',
    statusWarning: 'Varning',
    statusCritical: 'Kritisk',
    totalSensors: 'Totalt sensorer',
    tableTitle: 'Sensortabell',
    colSensorId: 'Sensor-ID',
    colLocation: 'Plats',
    colBattery: 'Batteri',
    colSignal: 'Signal',
    colStatus: 'Status',
    colLastSeen: 'Senast sedd',
    signalStrong: 'Stark',
    signalModerate: 'Måttlig',
    signalWeak: 'Svag',
    never: 'Aldrig',
    loading: 'Laddar...',
  },

  // Data Analysis page
  dataAnalysis: {
    title: 'Dataanalys',
    subtitle: 'Utforska bullermönster och trender',
    newAnalysis: 'Ny analys',
    filters: 'Filter',
    exportAll: 'Exportera alla',
    templatesTitle: 'Analysmallar',
    templateTimeseries: 'Dagligt genomsnitt per plats',
    templatePeak: 'Analys av rusningstider',
    templateComparison: 'Sensorjämförelse',
    templateWeekly: 'Veckotrender',
    typeLineChart: 'Linjediagram',
    typeBarChart: 'Stapeldiagram',
    typeAreaChart: 'Ytdiagram',
    timeRange: 'Tidsintervall',
    last1h: 'Senaste 1 timmen',
    last6h: 'Senaste 6 timmarna',
    last24h: 'Senaste 24 timmarna',
    modeAvg: 'Genomsnitt',
    modePeak: 'Toppvärde',
    distributionTitle: 'Mätningsfördelning',
    defaultChartTitle: 'Bulleranalys per timme',
    loading: 'Laddar diagramdata...',
    loadingDist: 'Laddar...',
    noData: 'Ingen data tillgänglig',
    tooltipAvg: 'Snitt',
    tooltipReadings: 'Mätningar',
  },

  // Reports page
  reports: {
    title: 'Rapporter',
    subtitle: 'Generera, schemalägg och hantera bullerövervakningsrapporter',
    generateTitle: 'Generera rapport',
    generateDesc: 'Skapa en ny rapport från aktuell data',
    generateBtn: 'Generera nu',
    scheduleTitle: 'Schemalägg rapport',
    scheduleDesc: 'Konfigurera automatiska återkommande rapporter',
    scheduleBtn: 'Ange schema',
    emailTitle: 'E-posta rapport',
    emailDesc: 'Skicka rapporter direkt till mottagare',
    emailBtn: 'Konfigurera e-post',
    scheduledTitle: 'Schemalagda rapporter',
    colReportName: 'Rapportnamn',
    colFrequency: 'Frekvens',
    colStatus: 'Status',
    colNextRun: 'Nästa körning',
    colActions: 'Åtgärder',
    editBtn: 'Redigera',
    pauseBtn: 'Pausa',
    recentTitle: 'Senaste rapporter',
    viewAll: 'Visa alla',
    colDate: 'Datum',
    colFormat: 'Format',
    colSize: 'Storlek',
    downloadLatest: 'Ladda ner senaste',
    statusActive: 'Aktiv',
    // Scheduled report names & frequencies
    dailyName: 'Daglig bullersammanfattning',
    weeklyName: 'Veckoanalysrapport',
    monthlyName: 'Månatlig sensorhälsa',
    dailyFreq: 'Varje dag kl. 08:00',
    weeklyFreq: 'Varje måndag kl. 09:00',
    monthlyFreq: 'Första dagen varje månad',
    nextTomorrow: 'Imorgon 08:00',
    nextMon: 'Mån 09:00',
    nextApr: '1 apr 08:00',
    // Recent report names
    sensorHealthReport: 'Sensorhälsorapport',
  },

  // Settings page
  settings: {
    title: 'Inställningar',
    subtitle: 'Konfigurera notifikationer, tröskelvärden och systeminställningar',
    navNotifications: 'Notifikationer',
    navThresholds: 'Tröskelvärden',
    navUsers: 'Användare & åtkomst',
    navSecurity: 'Säkerhet',
    notifTitle: 'Notifikationsinställningar',
    notifSubtitle: 'Välj vilka notifikationer du vill få',
    prefCriticalLabel: 'Kritiska larm',
    prefCriticalDesc: 'Omedelbar notifikation när sensorer överstiger kritiskt tröskelvärde',
    prefDailyLabel: 'Daglig sammanfattning',
    prefDailyDesc: 'Daglig sammanfattning av bullernivåer och sensorstatus',
    prefWeeklyLabel: 'Veckorapport',
    prefWeeklyDesc: 'Veckoanalysrapport med trender och insikter',
    prefMaintenanceLabel: 'Underhållspåminnelser',
    prefMaintenanceDesc: 'Larm när sensorer behöver underhållskontroll',
    thresholdsTitle: 'Larmtröskelvärden',
    thresholdsSubtitle: 'Ange dB-nivåer som utlöser larm',
    thresholdHighLabel: 'Hög bullernivå',
    thresholdHighDesc: 'Utlöser ett varningslarm',
    thresholdCriticalLabel: 'Kritisk bullernivå',
    thresholdCriticalDesc: 'Utlöser ett kritiskt larm',
    usersComingSoon: 'Användar- och åtkomsthantering kommer snart',
    securityComingSoon: 'Säkerhetsinställningar kommer snart',
    cancel: 'Avbryt',
    saveChanges: 'Spara ändringar',
    saved: 'Sparat!',
  },

  // Noise level labels (used in noise.js getNoiseLevelLabel)
  levels: {
    critical: 'Kritisk',
    high: 'Hög',
    moderate: 'Måttlig',
    normal: 'Normal',
  },

  // Placeholder pages
  placeholder: {
    notImplemented: 'Det här avsnittet är inte implementerat ännu.',
    notificationsDesc: 'Larmnotifikationer och händelsehistorik',
    systemDesc: 'Systemstatus och diagnostik',
  },
};

export default sv;
