// Swedish translations for the Malmö Noise Dashboard
const sv = {
  // Sidebar
  sidebar: {
    logo: 'Malmö Buller',
    logoSub: 'Övervakning',
    overview: 'Översikt',
    sensorMap: 'Sensorkarta',
    liveReadings: 'Livemätningar',
    alerts: 'Larm & Avvikelser',
    sensorHealth: 'Sensorhälsa',
    reports: 'Rapporter',
    settings: 'Inställningar',
    notifications: 'Notifikationer',
    system: 'System',
  },

  // Header
  header: {
    searchPlaceholder: 'Fråga AI om sensordata, bullernivåer eller få insikter...',
    ask: 'Fråga',
    admin: 'Admin',
  },

  // Overview page
  overview: {
    title: 'Översikt',
    subtitle: 'Systemövergripande sammanfattning av bullerovervakning',
    activeSensors: 'Aktiva sensorer',
    activeSensorsSubtitle: 'Med GPS-koordinater',
    maxNoise: 'Aktuell högsta nivå',
    maxNoiseSubtitle: 'Max livemätning över alla sensorer',
    maxNoiseSensor: 'Sensor-ID för högsta',
    maxNoiseSensorSubtitle: 'Sensor som rapporterar högsta nivån',
    activeAlerts: 'Aktiva larm',
    activeAlertsSubtitle: 'Sensorer vid 80 dB eller mer',
    sensorHealth: 'Sensorhälsa',
    sensorHealthSubtitle: 'Aktiva senaste 2 timmarna',
    chartTitle: 'Bullernivsöversikt',
    last1h: 'Senaste 1h',
    last6h: 'Senaste 6h',
    last24h: 'Senaste 24h',
    export: 'Exportera',
    range1h: '1 timme — 1 minuts genomsnitt',
    range6h: '6 timmar — 1 timmes genomsnitt',
    range24h: '24 timmar — 1 timmes genomsnitt',
    loading: 'Laddar instrumentpaneldata...',
    errorLoading: 'Fel vid laddning av data:',
    noData: 'Ingen historisk data tillgänglig',
  },

  // Sensor Map page
  sensorMap: {
    title: 'Sensorkarta',
    subtitle: 'Sensorplatser och aktuella bullernivåer',
    hideHeatZones: 'Dölj värmezoner',
    showHeatZones: 'Visa värmezoner',
    loading: 'Laddar kartdata...',
    sensorDetails: 'Sensordetaljer',
    sensorId: 'Sensor-ID',
    location: 'Plats',
    currentLevel: 'Aktuell nivå',
    lastUpdated: 'Senast uppdaterad',
    coordinates: 'Koordinater',
    clearSelection: 'Rensa val',
    clickPrompt: 'Klicka på en sensor på kartan för att se detaljer',
    legend: 'Bullernivslegend',
    legendNormal: 'Normal',
    legendModerate: 'Förhöjd',
    legendHigh: 'Varning',
    legendCritical: 'Kritisk',
  },

  // Live Readings page
  liveReadings: {
    title: 'Livemätningar',
    liveIndicator: 'Livemätning — uppdateras var 10:e sekund',
    loading: 'Laddar sensordata...',
    noData: 'Inga sensormätningar tillgängliga',
    guidelines: 'Utvärderingsriktlinjer',
    levelNormal: 'Normal',
    levelModerate: 'Förhöjd',
    levelHigh: 'Kräver uppmärksamhet',
    levelCritical: 'Omedelbar åtgärd krävs',
    descNormal: 'Säkert omgivningsbuller',
    descModerate: 'Förhöjt men acceptabelt',
    descHigh: 'Närmar sig osäkra nivåer',
    descCritical: 'Kräver omedelbar åtgärd',
  },

  // Alerts & Outliers page
  alerts: {
    title: 'Larm & Avvikelser',
    subtitle: 'Senaste 24 timmarna — avvikande bullermätningar',
    criticalBanner: (n) => `Kritiskt larm: ${n} sensor${n !== 1 ? 'er' : ''} överskred 90 dB de senaste 24 timmarna`,
    warningBanner: (n) => `Varning: ${n} mätning${n !== 1 ? 'ar' : ''} mellan 80–90 dB detekterades`,
    tableTitle: 'Bullermätningsavvikelser',
    filterAll: (n) => `Alla (${n})`,
    filterHigh: (n) => `${n} Höga avvikelser`,
    filterLow: (n) => `${n} Låga avvikelser`,
    exportCsv: 'Exportera CSV',
    loading: 'Laddar larm...',
    noOutliers: 'Inga avvikelser hittades de senaste 24 timmarna',
    colSensor: 'Sensor',
    colLocation: 'Plats',
    colReading: 'Mätning',
    colType: 'Typ',
    colTimestamp: 'Tidsstämpel',
    colNotes: 'Anteckningar',
    typeCritical: 'Omedelbar åtgärd krävs',
    typeHigh: 'Kräver uppmärksamhet',
    typeLow: 'Låg',
  },

  // Sensor Health page
  sensorHealth: {
    title: 'Sensorhälsa',
    subtitle: 'Statusöversikt för alla registrerade sensorer',
    exportReport: 'Exportera rapport',
    statusOperational: 'Operativ',
    statusWarning: 'Degraderad',
    statusCritical: 'Dålig',
    totalSensors: 'Totalt sensorer',
    tableTitle: 'Sensortabell',
    colSensorId: 'Sensor-ID',
    colLocation: 'Plats',
    colAvailability: 'Tillgänglighet (24 h)',
    colMaxGap: 'Max glapp',
    colStatus: 'Status',
    colLastSeen: 'Senast sedd',
    colReadings: 'Mätningar (24 h)',
    availabilityHint: 'Datatillgänglighetsgrad — observerade mätningar senaste 24 h jämfört med förväntat antal baserat på sensorns medianintervall för rapportering de senaste 30 dagarna',
    maxGapHint: 'Längsta sammanhängande tystnad mellan mätningar senaste 24 h',
    never: 'Aldrig',
    loading: 'Laddar...',
    noData: '—',
  },

  // Reports page
  reports: {
    title: 'Rapporter',
    subtitle: 'Välj rapporttyp, ange filter, förhandsgranska datan och ladda sedan ner som CSV eller PDF.',
    step1: 'Välj rapporttyp',
    step2: 'Ange filter',
    step3: 'Förhandsgranska & ladda ner',
    timeRange: 'Tidsintervall',
    sensor: 'Sensor',
    allSensors: 'Alla sensorer',
    noFiltersNeeded: 'Inga filter krävs för denna rapporttyp.',
    loading: 'Laddar data…',
    noData: 'Ingen data hittades för valda filter.',
    rowsReady: 'rader redo att exportera',
    downloadCsv: 'Ladda ner CSV',
    downloadPdf: 'Ladda ner PDF',
    types: {
      summary:      'Systemsammanfattning',
      alerts:       'Larm & Avvikelser',
      sensorHealth: 'Sensorhälsa',
      rawReadings:  'Rådata',
    },
    descs: {
      summary:      'Totaler, snitt och spann per sensor',
      alerts:       'Alla mätningar ≥ 80 dB eller < 25 dB senaste 24 h',
      sensorHealth: 'Status, batteri och senast sedd för varje sensor',
      rawReadings:  'Upp till 500 råmätningar (alla eller en sensor)',
    },
  },

  // Settings page
  settings: {
    title: 'Inställningar',
    subtitle: 'Konfigurera notifikationer, tröskelvärden och systeminställningar',
    navNotifications: 'Notifikationer',
    navThresholds: 'Tröskelvärden',
    navDashboard: 'Instrumentpanel',
    navUsers: 'Användare & åtkomst',
    navSecurity: 'Säkerhet',
    dashboardTitle: 'Instrumentpanelsinställningar',
    dashboardSubtitle: 'Styr hur instrumentpanelen beter sig',
    liveRefreshLabel: 'Uppdateringsintervall för livemätningar',
    liveRefreshDesc: 'Hur ofta sidan Livemätningar hämtar ny sensordata automatiskt',
    overviewRangeLabel: 'Standardtidsintervall för översikt',
    overviewRangeDesc: 'Vilket tidsfönster översiktens diagram öppnas med',
    darTitle: 'Sensorhälsotrösklar',
    darSubtitle: 'DAR-gränser för att klassificera sensorstatus',
    darOperationalLabel: 'Operativt tröskelvärde (DAR %)',
    darOperationalDesc: 'Sensorer vid eller över denna tillgänglighetsgrad klassificeras som operativa',
    darWarningLabel: 'Varning / Dålig-gräns (DAR %)',
    darWarningDesc: 'Sensorer under denna grad klassificeras som Dåliga; över den som Degraderade',
    seconds: 's',
    hours: 'h',
    notifTitle: 'Notifikationsinställningar',
    notifSubtitle: 'Välj vilka notifikationer du vill få',
    prefCriticalLabel: 'Kritiska larm',
    prefCriticalDesc: 'Omedelbar notifikation när sensorer överstiger kritiskt tröskelvärde',
    prefDailyLabel: 'Daglig sammanfattning',
    prefDailyDesc: 'Daglig sammanfattning av bullernivåer och sensorstatus',
    prefWeeklyLabel: 'Veckorapport',
    prefWeeklyDesc: 'Veckoanalysrapport med trender och insikter',
    prefMaintenanceLabel: 'Underhållspåminnelser',
    prefMaintenanceDesc: 'Larm när sensorer behöver underhållskontroll',
    thresholdsTitle: 'Larmtröskelvärden',
    thresholdsSubtitle: 'Ange dB-nivåer som utlöser larm',
    thresholdHighLabel: 'Varningsgräns (standard 80 dB)',
    thresholdHighDesc: 'Utlöser ett varningslarm — mätningar vid eller över denna nivå (80–90 dB)',
    thresholdCriticalLabel: 'Kritisk gräns (standard 90 dB)',
    thresholdCriticalDesc: 'Utlöser ett kritiskt larm — mätningar vid eller över denna nivå (90+ dB)',
    usersComingSoon: 'Användar- och åtkomsthantering kommer snart',
    securityComingSoon: 'Säkerhetsinställningar kommer snart',
    cancel: 'Avbryt',
    saveChanges: 'Spara ändringar',
    saved: 'Sparat!',
  },

  // Noise level labels (used in noise.js getNoiseLevelLabel)
  levels: {
    critical: 'Kritisk',
    high: 'Hög',
    moderate: 'Måttlig',
    normal: 'Normal',
  },

  // Placeholder pages
  placeholder: {
    notImplemented: 'Det här avsnittet är inte implementerat ännu.',
    notificationsDesc: 'Larmnotifikationer och händelsehistorik',
    systemDesc: 'Systemstatus och diagnostik',
  },
};

export default sv;
